"""Interfaz de repositorios de metadatos.

Centraliza el acceso a datos detrás de una interfaz. La implementación real es
DynamoDB single-table (app/db/dynamo.py).
"""

from __future__ import annotations

from typing import Optional, Protocol

from ..models import (
    ContactMessage,
    Folder,
    GlobalStats,
    LoginEvent,
    PasswordResetToken,
    Project,
    User,
)


class UserRepository(Protocol):
    def get_by_id(self, user_id: str) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_google_sub(self, sub: str) -> Optional[User]: ...
    def create(self, user: User) -> User: ...
    def update(self, user: User, *, previous_email: Optional[str] = None) -> User: ...
    def delete(self, user: User) -> None: ...
    # Admin: lista paginada. Devuelve (usuarios, cursor_siguiente|None).
    def list_all(self, limit: int = 50, cursor: Optional[str] = None) -> tuple[list[User], Optional[str]]: ...


class FolderRepository(Protocol):
    def list_for_owner(self, owner_id: str) -> list[Folder]: ...
    def get_owned(self, folder_id: str, owner_id: str) -> Optional[Folder]: ...
    def create(self, folder: Folder) -> Folder: ...
    def update(self, folder: Folder) -> Folder: ...
    def delete(self, folder: Folder) -> None: ...


class ProjectRepository(Protocol):
    def list_for_owner(self, owner_id: str) -> list[Project]: ...
    def get_owned(self, project_id: str, owner_id: str) -> Optional[Project]: ...
    def create(self, project: Project) -> Project: ...
    def update(self, project: Project) -> Project: ...
    def delete(self, project: Project) -> None: ...
    def reassign_folder(
        self, from_folder_id: str, to_folder_id: Optional[str], owner_id: str
    ) -> None: ...


class EventRepository(Protocol):
    def record_login(self, event: LoginEvent) -> None: ...
    def last_login_for(self, user_id: str) -> Optional[LoginEvent]: ...
    def recent_logins(self, limit: int = 20) -> list[LoginEvent]: ...


class ResetTokenRepository(Protocol):
    def create(self, token: PasswordResetToken) -> None: ...
    def get(self, token: str) -> Optional[PasswordResetToken]: ...
    def delete(self, token: str) -> None: ...


class ContactRepository(Protocol):
    def create(self, message: ContactMessage) -> ContactMessage: ...
    def list_recent(
        self, limit: int = 50, cursor: Optional[str] = None
    ) -> tuple[list[ContactMessage], Optional[str]]: ...


class StatsRepository(Protocol):
    def get(self) -> GlobalStats: ...
    def recompute(self) -> GlobalStats: ...
    def bump(
        self,
        user_delta: int = 0,
        project_delta: int = 0,
        role_deltas: Optional[dict[str, int]] = None,
    ) -> None: ...


class Repositories(Protocol):
    users: UserRepository
    folders: FolderRepository
    projects: ProjectRepository
    events: EventRepository
    reset_tokens: ResetTokenRepository
    contacts: ContactRepository
    stats: StatsRepository
