"""Interfaz de repositorios de metadatos.

Centraliza el acceso a datos (User/Folder/Project) detrás de una interfaz para
que el backend pueda cambiar entre SQL (SQLModel) y DynamoDB sin tocar los
routers. La implementación real es SQL (app/db/sql.py); DynamoDB es un stub de
preparación para producción (app/db/dynamo.py).
"""

from __future__ import annotations

from typing import Optional, Protocol

from ..models import Folder, Project, User


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def create(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...


class FolderRepository(Protocol):
    def list_for_owner(self, owner_id: int) -> list[Folder]: ...
    def get_owned(self, folder_id: int, owner_id: int) -> Optional[Folder]: ...
    def create(self, folder: Folder) -> Folder: ...
    def update(self, folder: Folder) -> Folder: ...
    def delete(self, folder: Folder) -> None: ...


class ProjectRepository(Protocol):
    def list_for_owner(self, owner_id: int) -> list[Project]: ...
    def get_owned(self, project_id: int, owner_id: int) -> Optional[Project]: ...
    def create(self, project: Project) -> Project: ...
    def update(self, project: Project) -> Project: ...
    def delete(self, project: Project) -> None: ...
    def reassign_folder(self, from_folder_id: int, to_folder_id: Optional[int], owner_id: int) -> None: ...


class Repositories(Protocol):
    users: UserRepository
    folders: FolderRepository
    projects: ProjectRepository
